### ISSUE TITLE
Duplicated APIs, http://localhost:8080/v1/swagger-ui/index.html

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#714] opened 2023-06-07 11:38 UTC
**Prerequisites:**
Start LDES Server with swagger api configured on the port 8080

On: http://localhost:8080/v1/swagger-ui/index.html

APIs :

- Update DCAT metadata for a LDES
- Add DCAT metadata for a LDES
- Delete DCAT metadata for a LDES

appear both under Event Streams section. 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/19c0056b-0210-43d2-9fee-68fddc4b0486)

and DCAT section:
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/5f1a3fff-a66b-4fe8-9949-d7586ed0b532)

I think these APIs should be only under the DCAT section?

**Comment by Tomvbe** [comment] 2023-06-07 11:55
This was intended behavior as it was not consistent between the views and eventstreams. I already made these endpoints already exclusively DCAT yesterday: https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/694/files#diff-398e215e886483bc85b1e0c176c4976b07f3fa67c9659a70c8c8eed5440ffbba

So this is already "fixed" in develop.

**Comment by Tomvbe** [comment] 2023-06-09 07:04
Closing this as it is not really an issue. The develop branch already has the desired tags. In case any other changes are desired, a github discussion could be opened.

**Closed by Tomvbe** 2023-06-09 07:04 UTC
Labels: documentation
