### ISSUE TITLE
ldes server cannot run for iow use case

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESServer4J#391] opened 2023-01-13 12:35 UTC
**Describe the bug**
LDES server fails while running this e2e use case: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/iow/3.ngsi-v2-to-ldes

**To Reproduce**
Perform the e2e test as described here: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/iow/3.ngsi-v2-to-ldes

**Error log**
```
dDependencyException: Error creating bean with name 'fragmentationExecutorImpl' defined in URL [jar:file:/lib/ldes-fragmentisers-geospatial-jar-with-dependencies.jar!/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fragmentationStrategyMap' defined in class path resource [be/vlaanderen/informatievlaanderen/ldes/server/domain/viewcreation/services/FragmentationStrategyConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'fragmentationStrategyMap' threw exception; nested exception is org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity using constructor public be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity(java.lang.String,java.lang.Boolean,java.lang.String,java.util.List,java.lang.Boolean,java.lang.Boolean,java.lang.String,java.time.LocalDateTime,int) with arguments /device-models-by-time,true,device-models-by-time,[],false,false,null,null,null
2023-01-13 12:29:43.823  INFO [,,] 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-01-13 12:29:43.859  WARN [,,] 1 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [BufferPoolPruner-1-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@18-ea/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@18-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@18-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@18-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@18-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@18-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@18-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@18-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@18-ea/java.lang.Thread.run(Thread.java:833)
2023-01-13 12:29:43.920  INFO [,,] 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-01-13 12:29:44.006 ERROR [,,] 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fragmentationExecutorImpl' defined in URL [jar:file:/lib/ldes-fragmentisers-geospatial-jar-with-dependencies.jar!/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/FragmentationExecutorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fragmentationStrategyMap' defined in class path resource [be/vlaanderen/informatievlaanderen/ldes/server/domain/viewcreation/services/FragmentationStrategyConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'fragmentationStrategyMap' threw exception; nested exception is org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity using constructor public be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity(java.lang.String,java.lang.Boolean,java.lang.String,java.util.List,java.lang.Boolean,java.lang.Boolean,java.lang.String,java.time.LocalDateTime,int) with arguments /device-models-by-time,true,device-models-by-time,[],false,false,null,null,null
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at be.vlaanderen.informatievlaanderen.ldes.server.Application.main(Application.java:9) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[ldes-server-application.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[ldes-server-application.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[ldes-server-application.jar:na]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[ldes-server-application.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fragmentationStrategyMap' defined in class path resource [be/vlaanderen/informatievlaanderen/ldes/server/domain/viewcreation/services/FragmentationStrategyConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'fragmentationStrategyMap' threw exception; nested exception is org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity using constructor public be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity(java.lang.String,java.lang.Boolean,java.lang.String,java.util.List,java.lang.Boolean,java.lang.Boolean,java.lang.String,java.time.LocalDateTime,int) with arguments /device-models-by-time,true,device-models-by-time,[],false,false,null,null,null
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        ... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'fragmentationStrategyMap' threw exception; nested exception is org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity using constructor public be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity(java.lang.String,java.lang.Boolean,java.lang.String,java.util.List,java.lang.Boolean,java.lang.Boolean,java.lang.String,java.time.LocalDateTime,int) with arguments /device-models-by-time,true,device-models-by-time,[],false,false,null,null,null
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        ... 41 common frames omitted
Caused by: org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity using constructor public be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity(java.lang.String,java.lang.Boolean,java.lang.String,java.util.List,java.lang.Boolean,java.lang.Boolean,java.lang.String,java.time.LocalDateTime,int) with arguments /device-models-by-time,true,device-models-by-time,[],false,false,null,null,null
        at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:290) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:102) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:523) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readDocument(MappingMongoConverter.java:491) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:427) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.convert.MappingMongoConverter.project(MappingMongoConverter.java:316) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.MongoTemplate$ProjectingReadCallback.doWith(MongoTemplate.java:3374) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2978) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2695) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.doFind(ExecutableFindOperationSupport.java:220) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.oneValue(ExecutableFindOperationSupport.java:132) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$6(AbstractMongoQuery.java:188) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.doExecute(AbstractMongoQuery.java:152) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:127) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:81) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at jdk.proxy2/jdk.proxy2.$Proxy125.findLdesFragmentEntityByRootAndViewName(Unknown Source) ~[na:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.LdesFragmentMongoRepository.retrieveRootFragment(LdesFragmentMongoRepository.java:66) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.ldesfragment.services.RootFragmentCreatorImpl.createRootFragmentForView(RootFragmentCreatorImpl.java:23) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.services.FragmentationStrategyCreatorImpl.createFragmentationStrategyForView(FragmentationStrategyCreatorImpl.java:34) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[na:na]
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.services.FragmentationStrategyConfig.fragmentationStrategyMap(FragmentationStrategyConfig.java:26) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.services.FragmentationStrategyConfig$$EnhancerBySpringCGLIB$$b02eede3.CGLIB$fragmentationStrategyMap$0(<generated>) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.services.FragmentationStrategyConfig$$EnhancerBySpringCGLIB$$b02eede3$$FastClassBySpringCGLIB$$39646847.invoke(<generated>) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.services.FragmentationStrategyConfig$$EnhancerBySpringCGLIB$$b02eede3.fragmentationStrategyMap(<generated>) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        ... 42 common frames omitted
Caused by: java.lang.IllegalArgumentException: Parameter numberOfMembers must not be null
        at org.springframework.util.Assert.notNull(Assert.java:201) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.fragment.entity.LdesFragmentEntity_Instantiator_enwxb3.newInstance(Unknown Source) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:288) ~[ldes-server-infra-mongo-jar-with-dependencies.jar:na]
        ... 88 common frames omitted
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20

**Additional context**
Git commit: [202664dd4e02e5766f5e05df5249c3f23205ed78](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/202664dd4e02e5766f5e05df5249c3f23205ed78)  

Docker tag:  [20221216T1458](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pkgs/container/ldes-server/59261442?tag=20221216T1458)

**Comment by Yalz** [comment] 2023-01-16 14:37
Hi Zargham,

Did you start from a clean database for this test or did you use an old existing mongoDB ?

**Comment by pj-cegeka** [comment] 2023-01-26 09:09
Hi Zargham,

We are unable to reproduce the bug. It should be fixed in the latest version.

**Closed by pj-cegeka** 2023-01-26 09:09 UTC
Labels: bug
