### ISSUE TITLE
Cannot invoke "String.length()" because "predicateNameSpace" is null

### ISSUE THREAD

**Issue by razoreater** [Informatievlaanderen/VSDS-LDESServer4J#1306] opened 2024-06-06 08:39 UTC
**Describe the bug**
After setting up a LDES stream, view and pipeline.
And then posting data trough the pipeline or via the server we receive the following error on the view:

**Cannot invoke "String.length()" because "predicateNameSpace" is null**

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/16701687/d41b736c-7f96-4fb2-b81a-645557801bab)

**To Reproduce**
Set-up the stream and pipeline with the following config:
See added zipfile for the config files:

[config_files.zip](https://github.com/user-attachments/files/15612364/config_files.zip)

1. lpdc.ttl for the streamconfig
2. by-page.ttl for the view
3. lpdc-pipeline.yaml for the pipeline
4. Fiche3.json for sample data

**Expected behavior**
The data is place on the LDES without issues and can be viewed on the stream

**Additional context**
We are testing this on version 2.14.0, and have no issues with the same config on version 2.10.0.

**Comment by Yalz** [comment] 2024-06-17 14:40
Intermediate update from @ferre-vaes (freely translated to English)

> The error is thrown in the IngestEndpointFilter.doFilterInternal en is caught by the AdminRestResponseEntityExceptionHandlerbut I don't see why that this filter is now throwing the error since there is no difference in when the code still used to work
The problem is between commit 6d17fdab2276fda002fc4b420855a3670785579f and 4189b1978f8047b41a3290f4c3d3b9885afa8f6c but there in between are commits that do not even compile so I can not test these using git bisect

**Comment by Yalz** [comment] 2024-06-24 13:37
Hi @razoreater ,
I noticed from your ES config that 
* you were missing your versionOfPath and timestampPath. Do not: 
* you stated to create versions. This will take in state objects and automatically generate the previously mentioned two statements from the ingested state object. For more detail, see [the version object creation vs state object creation](https://informatievlaanderen.github.io/VSDS-LDESServer4J/configuration/event-stream#create-version-objects-vs-ingest-version-objects). Note that we now, in the 3.x versions helped prevent ingesting version objects in a state object configured ES via shacl validation.
```
</lpdc> a ldes:EventStream ;
	tree:shape [ a shacl:NodeShape ];
	ldes:createVersions true .
```

So as far as i understand from the data you provided, you try to create a version object from an already versioned object, and then ingest it into an LDES that has been configured to allow only state objects ?
Did I understand that correctly?

**Comment by razoreater** [comment] 2024-06-25 06:48
Thanks for the feedback @Yalz , we try to test this as soon as possible.
And we'll keep you posted, this might take a while as the summer vacations almost start.

**Comment by Yalz** [comment] 2024-11-12 12:16
Closing this due to staleness

**Closed by Yalz** 2024-11-12 12:16 UTC
Labels: bug, to verify
