### ISSUE TITLE
Performance improvement: check unique constraints in db commit

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#1037] opened 2023-12-05 13:37 UTC
**Is your feature request related to a problem? Please describe.**
Checking the uniqueness of a field in code is not performant, and doesn't work in a multithreaded system.
As the select and insert are done outside of a transactional context, there is no guarantee that the database is in the same state when the member is inserted as how it was when the constraint was checked.
Also, checking the uniqueness requires a round trip to the db, which can be avoided.

**Describe the solution you'd like**
Determine the uniqueness by putting a constraint on the db, and catch the non-unique exception.

**Describe alternatives you've considered**
Keep as-is, as concurrency issue is theoretical. Performance issue is real though.

**Additional context**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/1673560/bfa15343-9c67-4fdd-8949-49b01601d9a5)

**Comment by Tomvbe** [comment] 2023-12-06 19:39
This is a duplicate of https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/998. We already fixed this in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1004.

**Comment by jeflaenen** [comment] 2023-12-08 09:34
Therefor, closed!

**Closed by jeflaenen** 2023-12-08 09:34 UTC
Labels: enhancement
